In [2]:
import pandas as pd
import json
import numpy as np

In [3]:
with open('data.json', "r") as file:
    data = json.load(file)

In [4]:
data = [i for data in data['data'][0]['cuaca'] for i in data]

In [5]:
df = pd.DataFrame(data)

In [6]:
df.rename(columns={'t': 'temperature',
                   'tcc': 'cloudiness',
                    'tp': 'rain',
                    'wd_deg': 'wind_direction',
                    'wd': 'wind_direction_from',
                    'wd_to': 'wind_direction_to',
                    'ws': 'wind_speed',
                    'hu': 'humidity',
                    'vs': 'visibility',
                    'vs_text': 'visibility_text',}, inplace=True)

In [7]:
df.drop(['weather','weather_desc','wind_direction_from','wind_direction_to','visibility','visibility_text','time_index','local_datetime','datetime','analysis_date','utc_datetime','image','weather_desc_en'],axis=1,inplace=True)

In [8]:
columns_order = ['temperature', 'humidity', 'wind_speed', 'wind_direction', 'rain', 'cloudiness']
df = df[columns_order]

In [9]:
df.to_csv('csv/json_data_converted.csv',index=False)

kolom yang dibutuhkan untuk inputan

Index(['temperature', 'humidity', 'wind_speed', 'wind_direction', 'rain',
       'cloudiness'],
      dtype='object')

In [10]:
df.columns

Index(['temperature', 'humidity', 'wind_speed', 'wind_direction', 'rain',
       'cloudiness'],
      dtype='object')

In [12]:
df

    temperature  humidity  wind_speed  wind_direction  rain  cloudiness
0            26        88         8.4             281   0.0          98
1            30        76         8.6              31   0.2          96
2            28        81         9.0              54   1.5         100
3            28        79         8.8              73   3.0         100
4            26        92         8.6              41   0.7         100
5            25        95         8.4              21   0.0         100
6            25        98         8.5              10   0.0          96
7            24        98         8.6             349   0.1          99
8            26        92         8.7              25   0.5         100
9            29        76         9.0              34   0.4         100
10           31        69         9.0              47   0.4          20
11           29        78         9.1              74   3.2          74
12           26        94         8.7              78   4.1          90
13           25        94         8.7              61   0.8          81
14           24        98         8.6              30   1.2          99
15           24        98         8.6              11   0.0          93
16           26        89         8.6             341   0.1         100
17           29        76         8.6             341   0.5          65
18           28        83         5.3              89   1.6          99
19           29        78         5.3              89   0.5          95
20           26        91         6.3             101   0.0          91
21           25        95         6.3             101   0.0          93