In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('csv/weather.csv')

In [21]:
df.drop(["id","city","visibility","snow"],axis=1,inplace=True)

In [22]:
datetime_columns = ['timestamp']

for column in datetime_columns:
  df[column] = pd.to_datetime(df[column])

In [23]:
encoded_desc = {e:i for i,e in enumerate(df["description"].unique())}
df["description"] = df["description"].map(encoded_desc)

encoded_desc = {e:i for i,e in enumerate(df["condition_type"].unique())}
df["condition_type"] = df["condition_type"].map(encoded_desc)

In [24]:
df.loc[df['description'] == 4]

,temperature,humidity,pressure,wind_speed,wind_direction,rain,cloudiness,description,condition_type,timestamp
58,25.18,89,1010,1.13,197,0.13,26,4,1,2024-10-27 23:09:08
60,29.79,67,1011,1.83,199,0.18,77,4,1,2024-10-28 01:09:08
74,24.07,94,1010,0.58,176,0.11,78,4,1,2024-10-28 15:09:08
75,23.68,96,1009,0.79,178,0.79,83,4,1,2024-10-28 16:09:08
76,23.61,98,1008,1.20,178,0.11,85,4,1,2024-10-28 17:09:08
...,...,...,...,...,...,...,...,...,...,...
585,24.27,98,1009,1.24,355,0.24,100,4,1,2024-11-19 02:50:33
586,24.42,98,1009,1.09,343,0.19,100,4,1,2024-11-19 03:50:33
599,23.35,97,1008,0.95,329,0.14,99,4,1,2024-11-19 16:50:33
600,23.01,98,1007,0.85,332,0.49,89,4,1,2024-11-19 17:50:33
601,22.99,98,1007,0.84,342,0.39,100,4,1,2024-11-19 18:50:33

In [25]:
df.loc[df['rain'] > 0].to_csv('csv/new_data_rain.csv',index=False)

In [26]:
df.loc[df['rain'] == 0].to_csv('csv/new_data_not_rain.csv',index=False)